-- CampusFix SQL Server schema overview.
-- In the running app these tables are generated by Entity Framework Core migrations.
-- ASP.NET Core Identity also creates its own user/role tables.

CREATE TABLE ServiceRequests (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Title NVARCHAR(150) NOT NULL,
    Description NVARCHAR(MAX) NOT NULL,
    Category NVARCHAR(50) NOT NULL,
    Priority NVARCHAR(20) NOT NULL,
    Status NVARCHAR(30) NOT NULL,
    Location NVARCHAR(100) NULL,
    CreatedAt DATETIME2 NOT NULL,
    UpdatedAt DATETIME2 NULL,
    CreatedByUserId NVARCHAR(450) NOT NULL,
    AssignedToUserId NVARCHAR(450) NULL,
    AttachmentUrl NVARCHAR(500) NULL
);

CREATE TABLE RequestComments (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    ServiceRequestId INT NOT NULL,
    UserId NVARCHAR(450) NOT NULL,
    CommentText NVARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME2 NOT NULL,
    CONSTRAINT FK_RequestComments_ServiceRequests
        FOREIGN KEY (ServiceRequestId) REFERENCES ServiceRequests(Id) ON DELETE CASCADE
);

CREATE TABLE RequestStatusHistory (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    ServiceRequestId INT NOT NULL,
    OldStatus NVARCHAR(30) NULL,
    NewStatus NVARCHAR(30) NOT NULL,
    ChangedByUserId NVARCHAR(450) NOT NULL,
    ChangedAt DATETIME2 NOT NULL,
    CONSTRAINT FK_RequestStatusHistory_ServiceRequests
        FOREIGN KEY (ServiceRequestId) REFERENCES ServiceRequests(Id) ON DELETE CASCADE
);
